name             'lttapp'
maintainer       'Alex Rozumiy'
maintainer_email 'alex@rozumiy.name'
license          'All rights reserved'
description      'Deploying rails target application'
long_description 'Deploys load testing target app from github.com/brain-geek/load_test_target_app'
version          '0.1.2'

depends 'nginx'
depends 'application_ruby'
depends 'rvm'